// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "websocket test": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/dfree1645/goa-websocket-study/design
// --out=$(GOPATH)\src\github.com\dfree1645\goa-websocket-study
// --version=v1.2.0-dirty

package client
